FROM python:3.10-slim

COPY 
WORKDIR /app


COPY requirements.txt .

RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir \
        torch==2.8.0 \
        torchvision==0.23.0 \
        --extra-index-url https://download.pytorch.org/whl/cpu && \
    pip install --no-cache-dir -r requirements.txt && \
    pip install python-multipart && \
    pip install python-multipart

COPY . .

EXPOSE 8000
CMD ["uvicorn", "modules.API.app:app", "--host", "0.0.0.0", "--port", "8000"]